"""empty message

Revision ID: 1aee91bbe0bc
Revises: 
Create Date: 2021-11-04 02:12:58.892091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aee91bbe0bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('items', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seo_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locations', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seo_locations')
    op.drop_table('seo_items')
    # ### end Alembic commands ###
